baseURL: "https://3dprintersking.com"
title: 3D Printers King
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: false
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives/
                  weight: 10
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Brands
                  url: brands/
                  weight: 10

        menu:
            main:
                - name: Home
                  url: /
                  weight: 10
                - name: Brands
                  url: "/brands/"
                  weight: 20
                - name: Affiliate Disclosure
                  url: "/affiliate-disclosure/"
                  weight: 40
                - name: Privacy Policy
                  url: "/privacy-policy/"
                  weight: 50
                - name: Search
                  url: search
                  weight: 60
                - name: Buying Guides
                  url: "/tags/buying-guides"
                  weight: 30
                - name: Contact
                  url: "/contact"
                  weight: 70



outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: # to enable google analytics, opengraph, twitter-cards and schema (this was: production  )
    description: "3D Printers King is the best place to find your next 3D Printer.  We try and test our 3D printers and take them through their paces to find the best ones, so you don't have to! About the Author: Hi My name is Chris and I am the main writer for 3D Printers King and has been into 3D Printing for the last couple of years.  I hope you enjoy the blog!"

    author: 3D Printers King
    # author: ["Me", "You"] # multiple authors

    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Reviews of the BEST 3D Printers"
        Content: >
            Welcome to 3dprintersking.com where we help you to make the right choice when purchasing your next 3D Printer! Browse our reviews and buying guides of the latest 3D printers.

            My name is Chris and I got into 3D Printing over the last couple of years, since then I have been documenting my findings on 3D Printing into this blog to share my opinion and reviews of the different 3D Printers out there.

            Check out our posts below. I hope you enjoy the site!
    cover:
      hidden: false # hide everywhere but not in structured data
      hiddenInList: false # hide on list pages and home
      hiddenInSingle: false # hide on single page

    editPost:
        URL: "/contact"
        Text: "Contact us" # edit text
        appendFilePath: true # to append file path to Edit link

    label:
        text: "3D Printers King"
        icon: /static/uploads/icon2.png
        iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: brands
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
